spring:
  application:
    name: test
  datasource:
    url: jdbc:h2:tcp://localhost/~/test1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    test.test: debug
server:
  port: 8081